Initial kayobe configuration for SIB biomed
stackhpc/sib-kayobe-config pull request #1
Opened 2018-09-05 16:47 UTC by jovial

2018-09-06 14:25 UTC, markgoddard requested changes
Looks like a good start at this.

2018-09-06 14:25 UTC, markgoddard commented on etc/kayobe/inspector.yml
> +  - system_name_physnet
If you add system_name_llc here it will add the switch hostname to ironic ports' local_link_connection/switch_info, then you can refer to switches by hostname in NGS rather than MAC.

2018-09-06 14:25 UTC, markgoddard commented on etc/kayobe/kolla.yml
> +    RUN pip install git+https://github.com/stackhpc/networking-generic-switch@stackhpc/1.0.0.1
This release is based on stackhpc/queens. It'll probably work, but if not you might need to backport the change to stackhpc/pike.

2018-09-06 14:25 UTC, markgoddard commented on etc/kayobe/inventory/group_vars/controllers/nova-compute-ironic.conf
> +consecutive_build_service_disable_threshold = 0
This goes in etc/kayobe/kolla/config/nova/nova-compute-ironic.conf

2018-09-06 14:25 UTC, markgoddard commented on etc/kayobe/inventory/group_vars/controllers/network-interfaces
> +internal_interface: "{{ oc_provision_interface }}.{{ internal_vlan }}"
Public interface required?

2018-09-06 14:25 UTC, markgoddard commented on etc/kayobe/inventory/group_vars/controllers/network-interfaces
> +wl_provision_interface: "{{ oc_provision_interface }}.{{ wl_provision_vlan }}"
Are there bare metal compute nodes?

2018-09-06 14:25 UTC, markgoddard commented on etc/kayobe/inventory/group_vars/seed/dns
> +# Don't manage resolv.conf - use the DHCP response from neutron on VSS.
We probably don't want this if we're managing the seed node's hypervisor (are we?)

2018-09-06 14:25 UTC, markgoddard commented on etc/kayobe/inventory/group_vars/seed/network-interfaces
> +oc_provision_bootproto: dhcp
We probably don't want this if we're managing the seed node's hypervisor (are we?)

2018-09-06 14:25 UTC, markgoddard commented on etc/kayobe/kolla.yml
> +kolla_docker_registry: "{{ docker_registry }}"
We don't currently have automation for deploying a registry on the seed, but it's easy enough to do. I think the commands are in the eod deploy notes.

2018-09-06 14:25 UTC, markgoddard commented on etc/kayobe/networks.yml
>  #public_net_name:
Are you using a single network for public and internal APIs?

2018-09-06 14:25 UTC, markgoddard commented on etc/kayobe/networks.yml
> +oob_wl_net_name: wl_oob
Unless specifically requested, it might be easier to use a single VLAN for both compute and control OOB.

2018-09-06 14:25 UTC, markgoddard commented on etc/kayobe/networks.yml
> +oc_provision_inspection_allocation_pool_end: 10.12.3.255
Finish at .254 since that's the end of the subnet.

2018-09-06 14:25 UTC, markgoddard commented on etc/kayobe/networks.yml
> +wl_oob_allocation_pool_end: 10.12.7.255
.254

2018-09-06 14:25 UTC, markgoddard commented on etc/kayobe/networks.yml
> +internal_allocation_pool_end: 10.12.4.255
.254

2018-09-06 14:25 UTC, markgoddard commented on etc/kayobe/networks.yml
> +storage_allocation_pool_end: 10.12.5.255
.254

2018-09-06 14:25 UTC, markgoddard commented on etc/kayobe/networks.yml
> +storagemgmt_allocation_pool_end: 10.12.6.255
.254

2018-09-06 14:25 UTC, markgoddard commented on etc/kayobe/networks.yml
> +oc_provision_physical_network: "{{ sib_mgmt_physical_network }}"
Did you say this was on a different network?

2018-09-06 14:25 UTC, markgoddard commented on etc/kayobe/neutron.yml
> +  - mlnx_sdn_assist
Is there an IB network?

2018-09-06 14:25 UTC, markgoddard commented on etc/kayobe/storage.yml
> +storage_lvm_groups: []
We should look at making this the default in kayobe, or possibly basing it on the docker storage driver.

2018-09-06 15:21 UTC, jovial commented on etc/kayobe/inventory/group_vars/controllers/network-interfaces
> +wl_provision_interface: "{{ oc_provision_interface }}.{{ wl_provision_vlan }}"
Yep, we have 8 bare metal compute nodes.

2018-09-06 15:27 UTC, jovial commented on etc/kayobe/inventory/group_vars/controllers/network-interfaces
> +internal_interface: "{{ oc_provision_interface }}.{{ internal_vlan }}"
We do not have a public network defined at this moment in time

2018-09-06 15:37 UTC, jovial commented on etc/kayobe/inventory/group_vars/seed/network-interfaces
> +oc_provision_bootproto: dhcp
I believe we have a dedicated server for the seed node

2018-09-06 15:37 UTC, jovial commented on etc/kayobe/inventory/group_vars/seed/dns
> +# Don't manage resolv.conf - use the DHCP response from neutron on VSS.
Not 100% sure this. I thought we were were using a dedicated server for the seed.

2018-09-06 15:37 UTC, jovial commented on etc/kayobe/networks.yml
> +oob_wl_net_name: wl_oob
In the questionnaire document - which has morphed into the design specification - these are separated.

2018-09-06 15:37 UTC, jovial commented on etc/kayobe/networks.yml
>  #public_net_name:
The public network has been left out of the design specification at this moment in time.

2018-09-06 16:20 UTC, jovial commented on etc/kayobe/inspector.yml
> +  - system_name_physnet
Added

2018-09-14 12:06 UTC, oneswig approved these changes
So far so good.

2018-09-14 12:08 UTC, merged

2018-09-17 12:58 UTC, markgoddard commented on etc/kayobe/inventory/group_vars/ctl-switches
> +  - "switchport trunk allowed vlan add {{ wl_oob_vlan }}"
Do these default to tagged? I'm not sure it would work having multiple untagged VLANs on a trunk.

2018-09-17 12:58 UTC, markgoddard commented on etc/kayobe/inventory/group_vars/ctl-switches
> +  - "switchport trunk allowed vlan add {{ oc_provision_vlan }}"
As above.

2018-09-17 12:58 UTC, markgoddard commented on etc/kayobe/ipa.yml
> +    version: "use-https"
Need to merge this and use master? Or a tag?